import {chromium} from 'playwright';
import {spawn} from 'node:child_process';
import {mkdir,mkdtemp,writeFile} from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
const root=process.cwd();
await mkdir('test-results',{recursive:true});
const temp=await mkdtemp(path.join(root,'test-results','e2e-'));
const python=process.platform==='win32'?path.join(root,'.venv','Scripts','python.exe'):path.join(root,'.venv','bin','python');
const server=spawn(python,['-m','uvicorn','backend.api:app','--host','127.0.0.1','--port','8766'],{cwd:root,env:{...process.env,WIND_DATA_MODE:'demo',WIND_DB:path.join(temp,'test.sqlite3')},windowsHide:true,stdio:['ignore','pipe','pipe']});
let logs='';server.stderr.on('data',b=>logs+=b);server.stdout.on('data',b=>logs+=b);
let browser;const checks=[];const errors=[];
try{
 let ready=false;for(let i=0;i<80;i++){try{if((await fetch('http://127.0.0.1:8766/api/bootstrap')).ok){ready=true;break}}catch{}await new Promise(r=>setTimeout(r,250))}assert(ready,logs);
 browser=await chromium.launch({channel:'chrome',headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:900},acceptDownloads:true});
 page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
 const goto=async(query='')=>{await page.goto('http://127.0.0.1:8766/workbench'+query);await page.getByRole('heading',{name:'地方债估值',exact:true}).waitFor();await page.waitForFunction(()=>!document.querySelector('.skeleton-table'))};
 await goto();assert.equal(await page.locator('.region-row').count(),37);assert.equal(await page.locator('.cell-button').count(),777);checks.push('完整矩阵：37 地区 × 21 列');
 await page.screenshot({path:'test-results/desktop-1440.png'});
 await page.setViewportSize({width:1920,height:1080});assert(await page.locator('.matrix-scroll').evaluate(el=>el.scrollWidth<=el.clientWidth+1));await page.screenshot({path:'test-results/desktop-1920.png'});checks.push('1920 全矩阵展示、1440 表内滚动');
 await page.setViewportSize({width:1440,height:900});
 await page.getByLabel('地区档位',{exact:true}).selectOption('3');assert.equal(await page.locator('.region-row').count(),18);
 await page.getByLabel('显示口径',{exact:true}).selectOption('general');await page.getByLabel('搜索地区',{exact:true}).fill('青海');assert.equal(await page.locator('.cell-button').count(),7);
 const zero=page.getByRole('button',{name:'青海省 一般债 3Y 0.0000',exact:true});await zero.click();await page.getByRole('dialog').waitFor();assert.match(await page.locator('.detail-result').innerText(),/0\.0000/);await page.keyboard.press('Escape');assert.equal(await page.getByRole('dialog').count(),0);assert(await zero.evaluate(el=>el===document.activeElement));checks.push('筛选、有效零值、详情与 Escape 焦点归还');
 await page.reload();await page.locator('.cell-button').first().waitFor();assert.equal(await page.getByLabel('搜索地区',{exact:true}).inputValue(),'青海');checks.push('URL 视图刷新恢复');
 await page.getByLabel('搜索地区',{exact:true}).fill('不存在');await page.getByRole('heading',{name:'未找到匹配地区'}).waitFor();await page.getByRole('button',{name:'清除筛选'}).click();
 await page.getByRole('button',{name:'选择评估日期'}).click();await page.getByRole('button',{name:'2026-09-06 当日无估值',exact:true}).click();await page.getByRole('heading',{name:'当日无估值数据',exact:true}).waitFor();assert.equal(await page.locator('.cell-button').count(),0);checks.push('无估值日期不填前值');
 await goto('?date=2026-09-02');assert.equal(await page.locator('.cell-button').count(),777);assert.equal(await page.locator('.cell-button').evaluateAll(nodes=>nodes.every(n=>n.textContent==='—')),true);checks.push('真实空组与日期无数据分开显示');
 await goto('?date=2026-09-08');await page.getByText('本次更新失败，当前显示上次成功结果。',{exact:false}).waitFor();assert.equal(await page.locator('.cell-button').count(),777);checks.push('重试失败保留成功矩阵');
 await goto('?date=2026-09-10&scope=special&region=上海');
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'导出数据',exact:true}).click();const csv=await download;await csv.saveAs(path.join(temp,'export.csv'));assert.match(csv.suggestedFilename(),/2026-09-10/);checks.push('CSV 导出');
 await page.getByRole('button',{name:'AI 助手',exact:true}).click();await page.getByRole('button',{name:'与另一天比较',exact:true}).click();await page.locator('.answer-data tbody tr').first().waitFor();assert.equal(await page.locator('.answer-data tbody tr').count(),1);assert.match(await page.locator('.answer').innerText(),/2026-09-09/);await page.screenshot({path:'test-results/comparison.png'});checks.push('助手两日比较及版本依据');
 await page.getByRole('button',{name:'生成当日摘要',exact:true}).click();await page.locator('.summary-highlights').waitFor();assert.match(await page.locator('.answer').innerText(),/未进行逐券归因/);checks.push('按范围生成摘要');
 await page.getByLabel('向 AI 助手提问',{exact:true}).fill('2026年9月10日第三档专项债10年估值');await page.getByRole('button',{name:'发送问题',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.answer')?.textContent?.includes('找到 18 个汇总位置'));assert.equal(await page.locator('.answer-data tbody tr').count(),18);checks.push('自然语言查询覆盖第三档 18 地区');
 await page.getByRole('button',{name:'关闭 AI 助手',exact:true}).click();
 await page.getByRole('button',{name:'数据源',exact:true}).click();await page.getByRole('heading',{name:'数据源',exact:true}).waitFor();await page.getByLabel('Wind Key',{exact:true}).fill('Bearer bad');await page.getByRole('button',{name:'检查配置',exact:true}).click();await page.getByRole('alert').waitFor();
 await page.getByLabel('Wind Key',{exact:true}).fill('DEMO_TEST_KEY');await page.getByRole('button',{name:'保存配置',exact:true}).click();await page.getByText('配置已加密保存在本机。连接与数据覆盖仍待验证。').waitFor();assert.equal(await page.getByLabel('Wind Key',{exact:true}).inputValue(),'');assert.equal(await page.evaluate(()=>localStorage.length+sessionStorage.length),0);await page.screenshot({path:'test-results/source.png'});checks.push('Wind 配置校验、无凭据回显及浏览器持久化');
 await page.getByRole('button',{name:'大模型配置',exact:true}).click();await page.getByRole('heading',{name:'大模型配置',exact:true}).waitFor();
 await page.locator('#model-url').fill('https://model.example/v1');await page.locator('#model-name').fill('demo-model');await page.locator('#model-key').fill('TEST_MODEL_KEY');
 await page.getByRole('button',{name:'显示 API Key',exact:true}).click();assert.equal(await page.locator('#model-key').getAttribute('type'),'text');
 await page.getByRole('button',{name:'保存配置',exact:true}).click();await page.getByText('配置已保存，可以测试模型连接。',{exact:true}).waitFor();assert.equal(await page.locator('#model-key').inputValue(),'');assert(await page.getByRole('button',{name:'测试连接',exact:true}).isEnabled());
 await page.reload();await page.locator('#model-name').waitFor();await page.waitForFunction(()=>document.querySelector('#model-name')?.value==='demo-model');
 await page.locator('#model-name').fill('unsaved');assert(await page.getByRole('button',{name:'测试连接',exact:true}).isDisabled());await page.getByRole('button',{name:'撤销修改',exact:true}).click();assert.equal(await page.locator('#model-name').inputValue(),'demo-model');
 await page.screenshot({path:'test-results/model-config.png'});await page.getByRole('button',{name:'清除配置',exact:true}).click();await page.getByText('已清除大模型配置。',{exact:true}).waitFor();assert.equal(await page.locator('#model-name').inputValue(),'');checks.push('大模型配置、Key 显隐与不回显、刷新恢复、撤销及清除');
 await goto('?date=2026-09-04');await page.getByRole('heading',{name:'该日期数据获取失败',exact:true}).waitFor();await page.getByRole('button',{name:'更新记录 2',exact:true}).click();await page.getByRole('button',{name:'运行演示更新',exact:true}).click();
 let published=false;for(let i=0;i<80;i++){const data=await fetch('http://127.0.0.1:8766/api/datasets/2026-09-04').then(r=>r.json());if(data.dataState==='ready'){published=true;break}await new Promise(r=>setTimeout(r,250))}assert(published,'Retry must atomically publish a ready snapshot');
 await goto('?date=2026-09-04');assert.equal(await page.locator('.cell-button').count(),777);await page.reload();await page.locator('.cell-button').first().waitFor();checks.push('从首次失败重试成功并在刷新后持久化');
 await page.screenshot({path:'test-results/retried.png'});
 await page.setViewportSize({width:390,height:844});await goto('?date=2026-09-10&scope=general');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'test-results/mobile.png'});await page.getByRole('button',{name:'AI 助手',exact:true}).click();assert(await page.getByLabel('向 AI 助手提问').isVisible());checks.push('390px 窄屏与助手布局');
 assert.deepEqual(errors,[]);checks.push('浏览器无脚本错误或控制台错误');
 await writeFile('test-results/browser-report.json',JSON.stringify({passed:checks.length,checks,errors},null,2));console.log(JSON.stringify({passed:checks.length,checks},null,2));
}finally{await browser?.close();server.kill();await writeFile(path.join(temp,'server.log'),logs)}
