import {useEffect,useRef,useState} from 'react';
import AppIcon from './AppIcon';
import {ArrowUp,ArrowUpRight,ChartNoAxesCombined,FileText,Search,Sparkles,X,LoaderCircle,Copy,Check} from 'lucide-react';
import {Cell,View,cohortName,scopeName,tierName,fmt,signed,post,scopes,YieldDefinition,Provider,providerName} from './data';
type Row=Cell&{regionName:string;baseYieldPct:string|null;changeBP:string|null;baseSampleCount:number|null;baseAmountYi:string|null;sampleChange:number|null;amountChangeYi:string|null;link:string};
type Result={groupingBasis?:string;yieldDefinition?:YieldDefinition;baseYieldDefinition?:YieldDefinition;comparisonBlocked?:boolean;mode:string;message:string;targetDate?:string;baseDate?:string;context?:View&{term?:number;regionIds?:string[]};status?:string;baseStatus?:string;publishedRunId?:string;baseRunId?:string;link?:string;rows?:Row[];highlights?:{termYears:number;bondScope:string;regionName:string;changeBP:string;sampleChange:number;amountChangeYi:string;link:string}[];note?:string};
export default function Assistant({view,maxDate,close,navigate,yieldDefinition,source,groupingBasis,priorityRules=false}:{priorityRules?:boolean;groupingBasis?:string;source:Provider;yieldDefinition:YieldDefinition;view:View;maxDate:string;close:()=>void;navigate:(url:string)=>void}){
 const durationGrouped=groupingBasis==='modified_duration';
 const [prompt,setPrompt]=useState('');const [term,setTerm]=useState('10');const [base,setBase]=useState('2026-09-09');const [busy,setBusy]=useState(false);const [result,setResult]=useState<Result|null>(null);const [error,setError]=useState('');const [copied,setCopied]=useState(false);const input=useRef<HTMLTextAreaElement>(null);
 const resultDurationGrouped=result?.groupingBasis!==undefined?result.groupingBasis==='modified_duration':durationGrouped;
 useEffect(()=>{if(result)document.querySelector('.answer')?.scrollIntoView({block:'start',behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})},[result]);
 async function submit(action:string,text=prompt){setBusy(true);setError('');try{setResult(await post<Result>('/analysis',{action,prompt:text,context:{...view,term:term?Number(term):null},baseDate:action==='compare'||/比较|对比|变化|涨跌/.test(text)?base:undefined}));setPrompt('')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function copy(){try{await navigator.clipboard.writeText(JSON.stringify(result,null,2));setCopied(true);setTimeout(()=>setCopied(false),2000)}catch{setError('剪贴板不可用，可直接选择回答文本复制')}}
 return <aside className="assistant-panel" aria-label="AI 助手"><header className="assistant-header"><span className="assistant-logo"><AppIcon kind="assistant"/></span><strong>AI 助手</strong><button className="icon-button" onClick={close} aria-label="关闭 AI 助手"><X/></button></header><div className="assistant-scroll"><div className="context-card"><strong>{view.date}</strong><span>{providerName(source)} · {yieldDefinition.label}</span>{source==='akshare'?<p className="source-help">{priorityRules?'逐券优先采用中债估值收益率，无则采用到期收益率。按个券直接久期、计算或估算久期、地方债指数久期参考的顺序分组。指数久期代理单独标识，指数与曲线收益率不作个券收益率。':<>按当前数据规则分析个券收益率；{durationGrouped?'使用个券修正久期分档，可能包含带假设的估算久期。':''}指数与曲线参考不用于个券汇总或涨跌排名。</>}</p>:null}<span>{cohortName(view.cohort)} · {view.region||tierName(view.tier)} · {scopeName(view.scope)}</span><div className="assistant-selects"><label>{durationGrouped?'久期档位':'期限'}<select aria-label={durationGrouped?'分析久期档位':'分析期限'} value={term} onChange={e=>setTerm(e.target.value)}><option value="">{durationGrouped?'全部久期档位':'全部期限'}</option>{[3,5,7,10,15,20,30].map(t=><option key={t} value={t}>{t}Y</option>)}</select></label><label>比较基准<input aria-label="比较基准日期" type="date" min="2026-09-01" max={maxDate} value={base} onChange={e=>setBase(e.target.value)}/></label></div></div>
 <div className="quick-actions"><button disabled={busy} onClick={()=>submit('query','')}><Search/>查询数据<ArrowUpRight/></button><button disabled={busy||!base} onClick={()=>submit('compare','')}><ChartNoAxesCombined/>与另一天比较<ArrowUpRight/></button><button disabled={busy} onClick={()=>submit('summary','')}><FileText/>生成当日摘要<ArrowUpRight/></button></div>
 {!result?<details className="example-prompts"><summary>示例问题</summary>{[durationGrouped?'上海市和北京市的10年久期档专项债收益率':'上海市和北京市的10年专项债收益率',durationGrouped?'2026年9月10日第三档专项债10年久期档收益率':'2026年9月10日第三档专项债10年收益率','生成当日摘要'].map(p=><button key={p} onClick={()=>{setPrompt(p);input.current?.focus()}}>{p}<ArrowUpRight/></button>)}</details>:null}
 {busy?<div className="analysis-loading" role="status"><LoaderCircle className="spin"/>正在分析…</div>:null}
 {error?<div className="inline-error" role="alert">{error}</div>:null}
 {result?<article className="answer"><div className="answer-title"><Sparkles/><strong>{result.mode==='summary'?'行情摘要':result.mode==='compare'?'历史对比':result.mode==='clarify'?'需要补充条件':'查询结果'}</strong><button className="icon-button" aria-label="复制分析结果" onClick={copy}>{copied?<Check/>:<Copy/>}</button></div>{result.targetDate?<div className="answer-context"><strong>目标 {result.targetDate}{result.baseDate?` · 基准 ${result.baseDate}`:''}</strong><span>{cohortName(result.context?.cohort||view.cohort)} · {result.context?.region||tierName(result.context?.tier||'all')} · {scopeName(result.context?.scope||'all')} · {result.context?.term?`${resultDurationGrouped?'久期档位 ':''}${result.context.term}Y`:resultDurationGrouped?'全部久期档位':'全部期限'}</span>{result.context?.regionIds?.length?<span>地区：{[...new Set(result.rows?.map(r=>r.regionName))].join('、')}</span>:null}</div>:null}<p>{result.message}</p>{result.yieldDefinition?<p className="answer-note">目标口径：{result.yieldDefinition.label}{result.baseYieldDefinition?`；基准口径：${result.baseYieldDefinition.label}`:''}</p>:null}{result.comparisonBlocked?<p className="inline-error" role="status">两日计算规则或收益率口径不同，未计算收益率变化及涨跌排序。</p>:null}
 {!result.comparisonBlocked&&result.highlights?.length?<div className="summary-highlights">{result.highlights.map(h=><button key={h.termYears+h.bondScope} onClick={()=>navigate(h.link)}><span>{resultDurationGrouped?'久期 ':''}{h.termYears}Y · {scopes.find(s=>s.id===h.bondScope)?.name}</span><strong>{h.regionName}<b>{signed(h.changeBP)} <small>BP</small></b></strong><small>组内绝对变化最大 · 样本 {signed(h.sampleChange,0)} 只 · 规模 {signed(h.amountChangeYi)} 亿元</small></button>)}</div>:null}
 {result.rows?.length?<details className="answer-data" open={result.mode!=='summary'}><summary>查看数据依据 · {result.rows.length} 个位置</summary><div className="answer-table-scroll"><table><thead><tr><th>地区 / 口径</th>{result.baseDate&&!result.comparisonBlocked?<th>基准日</th>:null}<th>目标日 %</th>{result.baseDate&&!result.comparisonBlocked?<th>变化 BP</th>:null}</tr></thead><tbody>{result.rows.map(r=><FragmentRow key={r.regionId+r.termYears+r.bondScope} row={r} durationGrouped={resultDurationGrouped} compare={!!result.baseDate&&!result.comparisonBlocked} navigate={navigate}/>)}</tbody></table></div></details>:null}
 {result.note?<p className="answer-note">{result.note}</p>:null}{result.publishedRunId?<div className="answer-evidence"><span>目标版本 {result.publishedRunId.slice(0,8)}{result.baseRunId?` / 基准版本 ${result.baseRunId.slice(0,8)}`:''}</span><button onClick={()=>navigate(result.link!)}>返回对应矩阵 <ArrowUpRight/></button></div>:null}</article>:null}
 </div><form className="assistant-composer" onSubmit={e=>{e.preventDefault();if(prompt.trim())submit('query')}}><div className="composer-box"><textarea ref={input} aria-label="向 AI 助手提问" placeholder={durationGrouped?'输入问题，例如：上海10年久期档专项债收益率':'输入问题，例如：上海10年专项债收益率'} value={prompt} maxLength={2000} onChange={e=>setPrompt(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();if(prompt.trim()&&!busy)submit('query')}}}/><div><span>Shift + Enter 换行</span><button type="submit" disabled={!prompt.trim()||busy} aria-label="发送问题"><ArrowUp/></button></div></div><p>规则助手 · 使用 {providerName(source)} 已保存数据</p></form></aside>
}
function FragmentRow({row:r,compare,navigate,durationGrouped}:{durationGrouped:boolean;row:Row;compare:boolean;navigate:(url:string)=>void}){return <tr><td><button className="answer-region" onClick={()=>navigate(r.link)}>{r.regionName}<ArrowUpRight/></button><small>{durationGrouped?'久期 ':''}{r.termYears}Y · {scopes.find(s=>s.id===r.bondScope)?.name}</small><details><summary>样本与规模</summary><p>目标：{r.sampleCount} 只 / {fmt(r.issueAmountSumYi,2)} 亿元</p>{r.indexDurationCount!=null?<p>其中指数久期参考 {r.indexDurationCount} 只；中债估值 {r.valuationYieldCount??0} 只 / 到期收益率 {r.ytmYieldCount??0} 只</p>:null}{compare?<><p>基准：{r.baseSampleCount??'不可用'} 只 / {fmt(r.baseAmountYi,2)} 亿元</p><p>变化：{signed(r.sampleChange,0)} 只 / {signed(r.amountChangeYi)} 亿元</p></>:null}</details></td>{compare?<td>{fmt(r.baseYieldPct)}</td>:null}<td>{fmt(r.yieldPct)}</td>{compare?<td className={r.changeBP!==null&&Number(r.changeBP)>0?'change-up':r.changeBP!==null&&Number(r.changeBP)<0?'change-down':''}>{signed(r.changeBP)}{r.changeBP===null?<small>缺少可比收益率</small>:null}</td>:null}</tr>}
