import Decimal from 'decimal.js';
export type Provider='akshare'|'wind'|'demo';
export const providerName=(provider?:string)=>provider==='akshare'?'AKShare':provider==='demo'?'演示':'Wind';
export type Region={id:string;name:string;tier:number;order:number};
export type YieldDefinition={metric:string;priceBasis:string;label:string;source:string};
export type RuleData={version:string;formula:string;cutoff?:string;terms?:number[];yieldDefinition?:YieldDefinition;clausePolicy?:string;dataAcceptance?:string;dateBasis?:string;groupingBasis?:string;yieldPriority?:string[];durationPriority?:string[];durationPolicy?:string};
export const hasPriorityRules=(rules?:RuleData|null)=>Boolean(rules?.version==='rules-akshare-v3-priority-yield-duration-reference'&&(rules.yieldPriority?.includes('chinabond_valuation')||rules.durationPriority?.includes('index_reference')));
export const closeYieldDefinition:YieldDefinition={metric:'ytm',priceBasis:'close',label:'收盘价到期收益率',source:'Wind'};
export const legacyYieldDefinition:YieldDefinition={metric:'chinabond_valuation',priceBasis:'valuation',label:'中债估值收益率',source:'中债'};
export type Cell={cohort:string;regionId:string;termYears:number;bondScope:string;cellState:string;yieldPct:string|null;sampleCount:number;issueAmountSumYi:string;weightedYieldSum:string;estimatedDurationCount?:number;indexDurationCount?:number;directDurationCount?:number;valuationYieldCount?:number;ytmYieldCount?:number};
export type Run={source?:Provider;runId:string;targetDate:string;triggerType:string;status:string;outcome:string|null;phase:string;createdAt:string;startedAt:string|null;finishedAt:string|null;message:string;counts:Record<string,number>|null;yieldDefinition?:YieldDefinition;rulesVersion?:string;rules?:RuleData};
export type Day={source:Provider;evaluationDate:string;dataState:string;latestAttempt:Run|null;yieldDefinition?:YieldDefinition;snapshot:{source:Provider;publishedRunId:string;publishedAt:string;rulesVersion:string;mappingVersion:string;regions:Region[];cells:Cell[];yieldDefinition?:YieldDefinition;rules?:RuleData;groupingBasis?:string}|null};
export type Bootstrap={mode:Provider;latestDate:string|null;latestSavedDate?:string|null;availableDates?:string[];historyStart:string;maxDate:string;regions:Region[];terms:number[];yieldDefinition?:YieldDefinition};
export type SavedFieldSource={source?:Provider;name:string;value:unknown;unit?:string|null;requestId:string;sessionId?:string;tableIndex?:number;rowIndex?:number;columnIndex?:number;sourceFunction?:string;sourceDate?:string;sourceUrl?:string;retrievedAt?:string;executionMode?:string;evidence?:string[]};
export type Substitution={field:string;label:string;actualMetric:string;value:string|number|null;unit?:string;isProxy:true;sourceFunction:string;sourceDate?:string};
export type DurationCalculation={status:'estimated'|'calculated'|'unavailable';modifiedYears:string|number|null;macaulayYears:string|number|null;bucketYears:number|null;methodVersion:string;assumptions:string[];missingFields:string[];reason:string;inputs:Record<string,unknown>};
export type YieldSelection={kind:'chinabond_valuation'|'ytm'|'unavailable';label:string;reason:string;sourceDate?:string|null;source?:unknown};
export type DurationSelection={kind:'direct'|'calculated'|'estimated'|'index_reference'|'unavailable';value:string|null;bucketYears:number|null;label:string;reason:string;sourceDate?:string|null;source?:unknown};
export const durationSelectionName=(kind?:DurationSelection['kind'])=>({direct:'个券直接久期',calculated:'个券计算久期',estimated:'个券估算久期',index_reference:'指数参考',unavailable:'未取得久期'}[kind||'unavailable']);
export const durationStatusName=(status?:DurationCalculation['status'])=>status==='estimated'?'估算':status==='calculated'?'计算值':status==='unavailable'?'不可计算':'来源值';
export const groupingLabel=(basis?:string)=>basis==='modified_duration'?'修正久期档位':'剩余期限分组';
export function durationBucketRange(bucket:number,terms=[3,5,7,10,15,20,30]){const index=terms.indexOf(bucket);if(index<0)return '按最近标准久期档位归组';const lower=index>0?(terms[index-1]+bucket)/2:0;const upper=index<terms.length-1?(bucket+terms[index+1])/2:null;return upper==null?`修正久期 ≥ ${lower} 年`:`${lower} 年 ${index===0?'<':'≤'} 修正久期 < ${upper} 年`}
export type SavedBond={yieldSelection?:YieldSelection;durationSelection?:DurationSelection;valuationYieldPct?:string|null;tradeYieldPct?:string|null;yieldMetric?:string;durationCalculation?:DurationCalculation;source?:Provider;yieldDate?:string|null;yieldPriceBasis?:string;staticSyncStatus?:'completed'|'pending'|'running'|'failed'|'unmapped';tradeNetPrice?:string|null;substitutions?:Substitution[];referenceFields?:Record<string,unknown>;code:string;bondId:string|null;name:string|null;issuer:string|null;regionId:string|null;bondType:string|null;issueDate:string|null;maturityDate:string|null;cohort:string|null;remainingYears:string|null;termYears:number|null;issueAmountYi:string|null;outstandingBalanceYi:string|null;couponPct:string|null;yieldPct:string|null;duration:string|null;closeNetPrice:string|null;currency:string|null;disposition:'eligible'|'incomplete'|'excluded'|'conflicted';reason:string;missingFields:string[];validationErrors:string[];fieldSources:Record<string,SavedFieldSource[]>;sessionIds:string[];requestIds:string[];codes?:string[];identityBasis?:'explicit_cross_market_links'};
export type SavedFacet={cohort:string|null;regionId:string|null;bondType:string|null;disposition:string;count:number};
export type SavedPage={evaluationDate:string;source?:Provider;version:string;total:number;page:number;pageSize:number;bonds:SavedBond[]};
export type SavedData={rules?:RuleData;groupingBasis?:string;source?:Provider;coverage?:{staticCompleted:number|null;observed:number|null;yieldAvailable?:number|null};facets?:SavedFacet[];fullSync?:{targetDate:string;completed?:number;discovered?:number;catalogComplete?:boolean;marketObserved?:number;marketWithDetails?:number;marketEligible?:number;updatedAt?:string};provenance?:{source:string;complete:false;origin:'verified_import'|'live_query'|'market_sync';collectedAt:string;runId?:string;dictionaryUrl?:string;queryCount?:number;batchLimit?:number};benchmarks?:Record<string,unknown>;evaluationDate:string;scope:'saved_sample';complete:false;rulesVersion:string;mappingVersion:string;yieldDefinition:YieldDefinition;counts:{bonds:number;eligible:number;incomplete:number;excluded:number;conflicted:number;requests:number;sessions:number;substitutions?:number;referenceOnly?:number;acquiredFields?:number;durationEstimated?:number;durationCalculated?:number;durationUnavailable?:number;durationDirect?:number;durationIndexReference?:number;eligibleDurationIndexReference?:number;yieldValuation?:number;yieldYtm?:number};bonds:SavedBond[];cells:Cell[];warnings:string[]};
export const savedDispositionName=(value:string)=>({eligible:'可纳入汇总',incomplete:'必需字段待补齐',excluded:'不符合汇总口径',conflicted:'返回值冲突'}[value]||value);
export function saveCsv(filename:string,rows:unknown[][]){const url=URL.createObjectURL(new Blob(['\uFEFF'+rows.map(row=>row.map(value=>'"'+String(value??'').replaceAll('"','""')+'"').join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const anchor=document.createElement('a');anchor.href=url;anchor.download=filename;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export const snapshotYieldDefinition=(snapshot:NonNullable<Day['snapshot']>)=>snapshot.yieldDefinition||legacyYieldDefinition;
export function downloadSavedMatrixCsv(data:SavedData,view:View,regions:Region[]){
 if(data.evaluationDate!==view.date)return;
 const names=new Map(regions.filter(region=>(view.tier==='all'||region.tier===Number(view.tier))&&region.name.includes(view.region)).map(region=>[region.id,region.name]));
 const cells=data.cells.filter(cell=>cell.cohort===view.cohort&&names.has(cell.regionId)&&(view.scope==='all'||cell.bondScope===(view.scope==='overall'?'all':view.scope)));
 saveCsv(`地方债-全国视图-已有数据-${data.evaluationDate}.csv`,[
  ['查询日期','数据范围','规则版本','收益率口径','价格口径','收益率来源','发行日期组','地区',`${groupingLabel(data.groupingBasis)}(年)`,'债券口径',`${data.yieldDefinition.label}(%)`,'样本数','发行规模(亿元)',...(data.groupingBasis==='modified_duration'?['其中估算久期样本数']:[]),...(hasPriorityRules(data.rules)?['其中指数久期参考样本数','采用中债估值样本数','采用到期收益率样本数']:[])],
  ...cells.map(cell=>[data.evaluationDate,'已有样本，覆盖未完整',data.rulesVersion,data.yieldDefinition.label,data.yieldDefinition.priceBasis,data.yieldDefinition.source,cohortName(cell.cohort),names.get(cell.regionId),`${cell.termYears}Y`,scopes.find(scope=>scope.id===cell.bondScope)?.name,cell.yieldPct,cell.sampleCount,cell.issueAmountSumYi,...(data.groupingBasis==='modified_duration'?[cell.estimatedDurationCount??'']:[]),...(hasPriorityRules(data.rules)?[cell.indexDurationCount??'',cell.valuationYieldCount??'',cell.ytmYieldCount??'']:[])])
 ]);
}
export const dayYieldDefinition=(day:Day|null,boot:Bootstrap|null=null)=>day?.snapshot?snapshotYieldDefinition(day.snapshot):day?.yieldDefinition||boot?.yieldDefinition||closeYieldDefinition;
export type View={date:string;cohort:string;tier:string;scope:string;region:string};
export const scopes=[{id:'all',name:'整体'},{id:'general',name:'一般债'},{id:'special',name:'专项债'}];
export const scopeName=(id:string)=>id==='overall'?'整体':id==='all'?'全部口径':scopes.find(s=>s.id===id)?.name||id;
export const cohortName=(id:string)=>id==='before_20250808'?'2025-08-08 前发行':'2025-08-08 当天及以后发行';
export const tierName=(id:number|string)=>({'1':'一档','2':'二档','3':'三档'}[String(id)]||'全部档位');
export function fmt(value:string|number|null|undefined,places=4){return value==null?'—':new Decimal(value).toDecimalPlaces(places,Decimal.ROUND_HALF_UP).toFixed(places)}
export function signed(value:string|number|null|undefined,places=2){return value==null?'—':`${new Decimal(value).gt(0)?'+':''}${fmt(value,places)}`}
export function time(value:string|null|undefined){return value?new Date(value).toLocaleString('sv-SE',{timeZone:'Asia/Shanghai'}):'—'}
export async function api<T>(path:string,options?:RequestInit):Promise<T>{const response=await fetch('/api'+path,{...options,headers:{'Content-Type':'application/json',...options?.headers}});if(!response.ok){const error=await response.json().catch(()=>({detail:'请求失败，请检查后端服务'}));throw new Error(typeof error.detail==='string'?error.detail:'输入格式有误，请检查后重试')}return response.json()}
export const post=<T>(path:string,body:unknown={})=>api<T>(path,{method:'POST',body:JSON.stringify(body)});
export function initialView():View{const p=new URLSearchParams(location.search);return {date:p.get('date')||'',cohort:p.get('cohort')==='on_or_after_20250808'?'on_or_after_20250808':'before_20250808',tier:['1','2','3'].includes(p.get('tier')||'')?p.get('tier')!:'all',scope:['overall','general','special'].includes(p.get('scope')||'')?p.get('scope')!:'all',region:p.get('region')||''}}
export function downloadCsv(day:Day,view:View){const definition=dayYieldDefinition(day);const regions=day.snapshot?.regions.filter(r=>(view.tier==='all'||r.tier===Number(view.tier))&&r.name.includes(view.region))||[];const names=new Map(regions.map(r=>[r.id,r.name]));const rows=day.snapshot?.cells.filter(c=>c.cohort===view.cohort&&names.has(c.regionId)&&(view.scope==='all'||c.bondScope===(view.scope==='overall'?'all':view.scope)))||[];const values=[['评估日期','结果版本','规则版本','收益率口径','价格口径','收益率来源','发行日期组','地区',`${groupingLabel(day.snapshot?.groupingBasis??day.snapshot?.rules?.groupingBasis)}(年)`,'债券口径',`${definition.label}(%)`,'样本数','发行规模(亿元)',...(hasPriorityRules(day.snapshot?.rules)?['其中指数久期参考样本数','其中估算久期样本数','采用中债估值样本数','采用到期收益率样本数']:[])],...rows.map(c=>[day.evaluationDate,day.snapshot!.publishedRunId,day.snapshot!.rulesVersion,definition.label,definition.priceBasis,definition.source,cohortName(c.cohort),names.get(c.regionId),`${c.termYears}Y`,scopes.find(s=>s.id===c.bondScope)?.name,c.yieldPct??'',c.sampleCount,c.issueAmountSumYi,...(hasPriorityRules(day.snapshot?.rules)?[c.indexDurationCount??'',c.estimatedDurationCount??'',c.valuationYieldCount??'',c.ytmYieldCount??'']:[])])];const url=URL.createObjectURL(new Blob(['\uFEFF'+values.map(row=>row.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`地方债收益率-${providerName(day.source)}-${day.evaluationDate}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
