import {useEffect,useRef,useState} from 'react';
import {Download,RefreshCw,Search,FileText} from 'lucide-react';
import {api,time,Cell} from './data';
import './trace.css';

type Session={id:string;run_id:string|null;target_date:string|null;purpose:string;created_at:string;request_count:number};
type RequestRow={id:string;stage:string;method:string;tool:string|null;started_at:string;status:string;http_status:number|null;error:string|null;response_sha256:string|null};
type Evidence={requestId:string;tableIndex:number;rowIndex:number;columnIndex:number;name:string;value:unknown;unit?:string};
type Observation={id:string;code:string;bond_id:string|null;disposition:string;reason:string;payload:Record<string,unknown>;field_sources:Record<string,Evidence[]>;mapping_version:string};
type Detail={request:unknown;response:unknown;parts:string[];error:string|null;response_sha256:string|null};

export default function TracePage({runId,cell}:{runId:string|null;cell:Cell|null}){
 const [sessions,setSessions]=useState<Session[]>([]),[selected,setSelected]=useState(''),[requests,setRequests]=useState<RequestRow[]>([]),[requestId,setRequestId]=useState(''),[detail,setDetail]=useState<Detail|null>(null),[records,setRecords]=useState<Observation[]>([]),[total,setTotal]=useState(0),[offset,setOffset]=useState(0),[observation,setObservation]=useState<Observation|null>(null),[error,setError]=useState(''),[tick,setTick]=useState(0);
 const session=sessions.find(s=>s.id===selected);
 const requestRef=useRef<HTMLElement>(null),observationRef=useRef<HTMLElement>(null);
 useEffect(()=>{if(requestId)requestRef.current?.scrollIntoView({block:'start'})},[requestId]);
 useEffect(()=>{if(observation)observationRef.current?.scrollIntoView({block:'start'})},[observation]);
 useEffect(()=>{const c=new AbortController();setError('');api<Session[]>('/trace/sessions'+(runId?'?runId='+encodeURIComponent(runId):''),{signal:c.signal}).then(rows=>{setSessions(rows);setSelected(s=>rows.some(r=>r.id===s)?s:rows[0]?.id||'')}).catch(e=>{if(e.name!=='AbortError')setError(e.message)});return()=>c.abort()},[runId,tick]);
 useEffect(()=>{setOffset(0);setObservation(null);setRequestId('');setDetail(null)},[selected,cell]);
 useEffect(()=>{if(!selected)return;const c=new AbortController();setRequests([]);api<RequestRow[]>(`/trace/sessions/${selected}/requests`,{signal:c.signal}).then(setRequests).catch(e=>{if(e.name!=='AbortError')setError(e.message)});return()=>c.abort()},[selected,tick]);
 useEffect(()=>{setRecords([]);setTotal(0);if(!session?.run_id)return;const c=new AbortController();const params=new URLSearchParams({offset:String(offset),limit:'50'});if(cell){params.set('cohort',cell.cohort);params.set('region',cell.regionId);params.set('term',String(cell.termYears));params.set('scope',cell.bondScope)}api<{items:Observation[];total:number}>(`/trace/runs/${session.run_id}/observations?${params}`,{signal:c.signal}).then(data=>{setRecords(data.items);setTotal(data.total)}).catch(e=>{if(e.name!=='AbortError')setError(e.message)});return()=>c.abort()},[session?.run_id,offset,cell,tick]);
 useEffect(()=>{setDetail(null);if(!requestId)return;const c=new AbortController();api<Detail>(`/trace/requests/${requestId}`,{signal:c.signal}).then(setDetail).catch(e=>{if(e.name!=='AbortError')setError(e.message)});return()=>c.abort()},[requestId,tick]);
 return <section className="page trace-page"><div className="page-heading"><h1>Wind 历史溯源</h1><button className="button secondary" onClick={()=>setTick(t=>t+1)}><RefreshCw/>刷新记录</button></div>
 {error?<div className="inline-error" role="alert">{error}</div>:null}
 <div className="trace-select"><label htmlFor="trace-session">取数记录</label><select id="trace-session" value={selected} onChange={e=>setSelected(e.target.value)}>{sessions.map(s=><option key={s.id} value={s.id}>{s.target_date||'未指定日期'} · {s.purpose} · {time(s.created_at)} · {s.id.slice(0,8)}</option>)}</select>{session?<a className="button secondary" href={`/api/trace/sessions/${session.id}/export`} download><Download/>导出完整溯源 JSON</a>:null}</div>
 {!sessions.length?<div className="empty-state"><FileText/><h2>暂无可用 Wind 溯源记录</h2><p>完成 Wind 取数后可在这里查看原始数据；AKShare 来源在已有个券详情中查看。</p></div>:<>
 <details className="trace-metadata"><summary>记录信息</summary><p>{session?.run_id?`关联任务 ${session.run_id}`:'独立核验记录'}</p><p>导出包含全部请求与逐券明细，不包含鉴权 Key。</p></details>
 <section className="trace-card"><h2>工具请求 <small>{requests.length} 次</small></h2><div className="trace-scroll"><table><thead><tr><th>阶段</th><th>工具</th><th>状态</th><th>时间</th><th>原始数据</th></tr></thead><tbody>{requests.map(r=><tr key={r.id}><td>{r.stage}</td><td>{r.tool||r.method}</td><td><span className={`badge ${r.status==='failed'?'danger':r.status==='succeeded'?'success':'neutral'}`}>{r.status==='failed'?'失败':r.status==='succeeded'?'已返回':r.status==='interrupted'?'已中断':'请求中'}</span>{r.http_status?<small>HTTP {r.http_status}</small>:null}</td><td>{time(r.started_at)}</td><td><button className="text-button" onClick={()=>setRequestId(r.id)}>查看请求与响应</button></td></tr>)}</tbody></table></div></section>
 {requestId?<section ref={requestRef} className="trace-card" aria-label="原始请求详情"><div className="trace-card-title"><h2>原始请求与响应</h2><button className="text-button" onClick={()=>setRequestId('')}>收起</button></div><p className="source-help">请求编号 {requestId}</p>{detail?<><p className="trace-note">响应 SHA-256：{detail.response_sha256||'未形成完整响应，可查看接收记录'}</p><details open><summary>请求参数</summary><pre>{JSON.stringify(detail.request,null,2)}</pre></details><details open><summary>原始响应（含工具返回的完整文本）</summary><pre>{JSON.stringify(detail.response,null,2)}</pre></details>{detail.error?<div className="inline-error">{detail.error}</div>:null}<details><summary>接收记录（包含失败前收到的内容）</summary><pre>{detail.parts.join('')}</pre></details></>:<p>正在读取原始数据…</p>}</section>:null}
 <section className="trace-card"><h2>逐券合并与筛选 <small>{total} 条{cell?' · 当前汇总分组':''}</small></h2><div className="trace-scroll"><table><thead><tr><th>证券代码</th><th>稳定身份</th><th>处理结果</th><th>依据</th><th>字段来源</th></tr></thead><tbody>{records.map(row=><tr key={row.id}><td>{row.code}</td><td>{row.bond_id||'未确认'}</td><td>{{included:'纳入',excluded:'剔除',duplicate:'去重',conflict:'冲突'}[row.disposition]||row.disposition}</td><td>{row.reason}</td><td><button className="text-button" onClick={()=>setObservation(row)}><Search/>查看字段</button></td></tr>)}</tbody></table></div>{!total?<p className="source-help">暂无匹配结果，可查看工具原始响应。</p>:null}<div className="trace-pagination"><button className="button secondary" disabled={offset===0} onClick={()=>setOffset(n=>Math.max(0,n-50))}>上一页</button><span>{total?offset+1:0}—{Math.min(offset+50,total)} / {total}</span><button className="button secondary" disabled={offset+50>=total} onClick={()=>setOffset(n=>n+50)}>下一页</button></div></section>
 {observation?<section ref={observationRef} className="trace-card" aria-label="逐券字段详情"><div className="trace-card-title"><h2>{observation.code} · 字段来源</h2><button className="text-button" onClick={()=>setObservation(null)}>收起</button></div><p className="source-help">映射版本 {observation.mapping_version} · 表、行、列位置从 0 开始编号</p><details><summary>规范化输入与校验问题</summary><pre>{JSON.stringify(observation.payload,null,2)}</pre></details><div className="trace-scroll"><table><thead><tr><th>计算字段</th><th>Wind 原字段</th><th>原值 / 单位</th><th>来源位置</th></tr></thead><tbody>{Object.entries(observation.field_sources).flatMap(([field,items])=>items.length?items.map((e,i)=><tr key={field+i}><td>{field}</td><td>{e.name}</td><td>{JSON.stringify(e.value)} {e.unit||''}</td><td><button className="text-button" onClick={()=>setRequestId(e.requestId)}>表 {e.tableIndex} / 行 {e.rowIndex} / 列 {e.columnIndex}</button></td></tr>):<tr key={field}><td>{field}</td><td colSpan={3}>未返回可匹配字段</td></tr>)}</tbody></table></div></section>:null}
 </>}
 </section>
}
